server:
  port: 1111
spring:
  application:
    name: erueka-server

eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1112/eureka